server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ah-rest-useraccount
          uri: lb://AH-REST-USERACCOUNT
          predicates:
            - Path=/api/v1/useraccount/**

        - id: ah-rest-email
          uri: lb://AH-REST-EMAIL
          predicates:
            - Path=/api/v1/email/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
