server:
  port: 8080

spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

# secrets & Arthub's Config
arthub:
  ms:
    secrets:
      user-id-by-token: ${MS_MSG_KEY}
  infra:
    dev-mode: ${INFRA_DEV_MODE}