server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/useraccount/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/email/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
