# DOCKER COMPOSE PARA AMBIENTE DE PRODUÇÃO USANDO SQL SERVER DA AZURE
# Arthub 2024 Todos os direitos reservados

version: '3.8'

services:
  eureka-server:
    build:
      context: ./ah-rest-eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - ah_network

  api-gateway:
    build:
      context: ./ah-rest-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - INFRA_PROD_MODE=${PROD_MODE}
    networks:
      - ah_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api-gateway:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  email-ms:
    build:
      context: ./ah-rest-email
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - api-gateway
      - rabbitmq
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - INFRA_PROD_MODE=${PROD_MODE}
      - MS_MSG_KEY=${MS_SECRET_MSG_KEY}
      - SPRING_PROFILE=${SPRING_PROFILE}
    networks:
      - ah_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://email-ms:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  useraccount-ms:
    build:
      context: ./ah-rest-useraccount
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - api-gateway
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://${AZURE_SQL_SERVER_NAME}.database.windows.net:1433;database=${AZURE_SQL_DB_NAME};encrypt=true;trustServerCertificate=false;loginTimeout=30;
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SPRING_DATASOURCE_USERNAME=${AZURE_SQL_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${AZURE_SQL_DB_PASSWORD}
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - INFRA_PROD_MODE=${PROD_MODE}
      - MS_MSG_KEY=${MS_SECRET_MSG_KEY}
      - SPRING_PROFILE=${SPRING_PROFILE}
    networks:
      - ah_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://useraccount-ms:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  art-ms:
    build:
      context: ./ah-rest-art
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - api-gateway
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://${AZURE_SQL_SERVER_NAME}.database.windows.net:1433;database=${AZURE_SQL_DB_NAME};encrypt=true;trustServerCertificate=false;loginTimeout=30;
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SPRING_DATASOURCE_USERNAME=${AZURE_SQL_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${AZURE_SQL_DB_PASSWORD}
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - INFRA_PROD_MODE=${PROD_MODE}
      - MS_MSG_KEY=${MS_SECRET_MSG_KEY}
      - SPRING_PROFILE=${SPRING_PROFILE}
    networks:
      - ah_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://art-ms:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  comission-ms:
    build:
      context: ./ah-rest-comission
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - api-gateway
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://${AZURE_SQL_SERVER_NAME}.database.windows.net:1433;database=${AZURE_SQL_DB_NAME};encrypt=true;trustServerCertificate=false;loginTimeout=30;
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SPRING_DATASOURCE_USERNAME=${AZURE_SQL_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${AZURE_SQL_DB_PASSWORD}
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - INFRA_PROD_MODE=${PROD_MODE}
      - MS_MSG_KEY=${MS_SECRET_MSG_KEY}
      - SPRING_PROFILE=${SPRING_PROFILE}
    networks:
      - ah_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://comission-ms:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ah_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  ah_network:
    driver: bridge
